name: Deploy on GH-Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cacheNodeModules
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: yarn install
      if: steps.cacheNodeModules.outputs.cache-hit != 'true'
      run: yarn install
      env:
        CI: true
    - name: yarn build
      run: yarn build
      env:
        CI: true
    - name: deploy
      run: yarn deploy
      env:
        CI: true
